name: Automated Testing

on:
  pull_request:
    branches: [ master ]
    paths:
      - application/app/**

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: z-wear-project

      - name: Initialize
        working-directory: z-wear-project
        run: |
          pip3 install -U west
          west init -m https://github.com/nrfconnect/sdk-nrf --mr v1.6.0-rc2
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Run all tests
        working-directory: z-wear-project
        run: |
          zephyr/scripts/twister --coverage -p native_posix -p nrf52840dk_nrf52840 -T application/app/tests/ -W
          
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: z-wear-project/twister-out/twister_report.xml

      - name: Prepare the coverage file
        working-directory: z-wear-project
        shell: bash
        run: |
          grep -B 9999999 "modules/crypto/tinycrypt/lib/source/hmac.c" twister-out/coverage.info > twister-out/coverage_edited.info
          
      - name: Prepare the coverage file 2
        working-directory: z-wear-project
        shell: bash
        run: |
          head -n-2 twister-out/coverage_edited.info > twister-out/coverage_edited2.info

      - name: Code coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: z-wear-project/twister-out/coverage_edited2.info