name: Size Delta on Pull Requests

on:
  pull_request:
    branches: [ master ]
    paths:
      - application/app/**
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: z-wear-project
          
      - name: Install the required tools
        working-directory: z-wear-project
        run: |
          sudo apt update
          sudo apt upgrade -y
          wget https://apt.kitware.com/kitware-archive.sh
          sudo bash kitware-archive.sh
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev -y
      
      - name: Install west and nRF Connect SDK
        working-directory: z-wear-project
        run: |
          pip3 install --user west
          west init -m https://github.com/nrfconnect/sdk-nrf --mr v1.7.0
          west update
          west zephyr-export

      - name: Install additional Python dependencies
        working-directory: z-wear-project
        run: |
          pip3 install -r zephyr/scripts/requirements.txt
          pip3 install -r nrf/scripts/requirements.txt
          pip3 install -r bootloader/mcuboot/scripts/requirements.txt

      - name: Install the GNU Arm Embedded Toolchain
        working-directory: z-wear-project
        shell: bash
        run: |
          mkdir ~/gnuarmemb
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
          sudo tar xjf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 -C ~/gnuarmemb
          export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
          export GNUARMEMB_TOOLCHAIN_PATH="~/gnuarmemb/gcc-arm-none-eabi-9-2019-q4-major"
          source zephyr/zephyr-env.sh 

      - name: Dependencies for Code Size Delta
        working-directory: z-wear-project
        run: |
          sudo apt install binutils-arm-none-eabi
          pip install psycopg2-binary
          pip install click
          pip install prettytable

      - name: Build firmware
        working-directory: z-wear-project
        run: |
          export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
          export GNUARMEMB_TOOLCHAIN_PATH="~/gnuarmemb/gcc-arm-none-eabi-9-2019-q4-major"
          west build -b nrf52840dk_nrf52840 -s application/app
          
      - name: Diff revision
        id: diff_rev
        shell: bash
        working-directory: z-wear-project
        run: |
          delta=$(python3 application/codesizes.py diff build/zephyr/zephyr.elf)
          delta="${delta//'%'/'%25'}"
          delta="${delta//$'\n'/'%0A'}"
          delta="${delta//$'\r'/'%0D'}"
          echo "::set-output name=delta_code::$delta"
          
      - name: Auto Comment
        uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            👋 @{{ author }}
      
            Thank you for raising your pull request.
      
            This is the code delta:
      
            ```
      
            ${{ steps.diff_rev.outputs.delta_code }}
      
            ```
      
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.